# -*- coding: utf-8 -*-
"""proposed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CAx1ch8RVOWtLKBaLt-5ZmSs5AZfr_C
"""

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/abstracts.csv")
texts = df["text"].tolist()
labels = df["label"].values

encoder = SentenceTransformer("all-MiniLM-L6-v2")
X_embed = encoder.encode(texts, show_progress_bar=True)

pca = PCA(n_components=4)
X_pca = pca.fit_transform(X_embed)

scaler = MinMaxScaler(feature_range=(0, np.pi))
X_scaled = scaler.fit_transform(X_pca)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, labels, test_size=0.25, random_state=42
)

pip install pennylane

import pennylane as qml
import torch

n_qubits = 4
dev = qml.device("default.qubit", wires=n_qubits)

@qml.qnode(dev, interface="torch")
def quantum_circuit(x, weights):
    # Encoding
    for i in range(n_qubits):
        qml.RY(x[i], wires=i)

    # Entanglement
    for i in range(n_qubits - 1):
        qml.CNOT(wires=[i, i + 1])

    # Variational layer
    for i in range(n_qubits):
        qml.RY(weights[i, 0], wires=i)
        qml.RZ(weights[i, 1], wires=i)

    return qml.expval(qml.PauliZ(0))

weights = torch.randn((n_qubits, 2), requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

def loss_fn(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

epochs = 20

for epoch in range(epochs):
    total_loss = 0
    for x, y in zip(X_train, y_train):
        x_t = torch.tensor(x, dtype=torch.float32)
        y_t = torch.tensor(y, dtype=torch.float32)

        optimizer.zero_grad()
        out = quantum_circuit(x_t, weights)
        pred = sigmoid(out)
        loss = loss_fn(pred, y_t)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss/len(X_train):.4f}")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_preds = []

for x in X_test:
    x_t = torch.tensor(x, dtype=torch.float32)
    out = quantum_circuit(x_t, weights)
    y_preds.append(int(sigmoid(out).item() > 0.5))

print("Accuracy:", accuracy_score(y_test, y_preds))
print("Precision:", precision_score(y_test, y_preds))
print("Recall:", recall_score(y_test, y_preds))
print("F1:", f1_score(y_test, y_preds))